### ISSUE TITLE
低版本兼容问题

### ISSUE THREAD

**Issue by daidaijie** [ChyengJason/ToolBarHideAuto#1]
在Android4.2版本中,Toolbar只隐藏了其内容

**Comment by daidaijie** [comment]
我看错了

**Comment by ChyengJason** [comment]
放弃了



发自我的小米手机在 李宇杰 <notifications@github.com>，2018年3月22日 11:24写道：在Android4.2版本中,Toolbar只隐藏了其内容

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ChyengJason/ToolBarHideAuto","title":"ChyengJason/ToolBarHideAuto","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ChyengJason/ToolBarHideAuto"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"低版本兼容问题 (#1)"}],"action":{"name":"View Issue","url":"https://github.com/ChyengJason/ToolBarHideAuto/issues/1"}}}
